name: Publish Container

on: [ push ]

jobs:
  drf-todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Publish the container
        run: |
          docker build . --tag ghcr.io/k1lgor/drf-todo:latest
          docker run ghcr.io/k1lgor/drf-todo:latest
          docker push ghcr.io/k1lgor/drf-todo:latest
