name: Publish Container

on: [ push ]

jobs:
  drf-todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          echo $CR_PAT | docker login ghcr.io -u k1lgor --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - name: Publish the container
        run: |
          docker build . --tag ghcr.io/k1lgor/drf-todo:latest
          docker run ghcr.io/k1lgor/drf-todo:latest
          docker push ghcr.io/k1lgor/drf-todo:latest